# version: "3.9"

# services:
#   backend:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: bain_backend_prod
#     command: uvicorn app.main:app --host 0.0.0.0 --port 8000
#     ports:
#       - "8000:8000"
#     env_file:
#       - .env.prod
#     depends_on:
#       - db
#     restart: always

#   db:
#     image: postgres:15
#     container_name: postgres_db_prod
#     restart: always
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: bain_db
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data_prod:/var/lib/postgresql/data

# volumes:
#   postgres_data_prod:
